# Generated by Django 2.2.5 on 2019-09-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joyle_app', '0002_auto_20190928_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='fashionandstyle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='forbusiness',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='hobbysport',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='subcateg_transp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joyle_app.Subcategtransport', verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Стоимость'),
        ),
    ]
